spring:
    profile: local
    datasource:
        url: ${DATABASE_URL}
        username: ${USER_NAME}
        password: ${PASSWORD}
        test-on-borrow: true
        validation-query: SELECT 1 FROM dual
    flyway:
        locations: classpath:/db/migration
    jpa:
        show-sql: true
        hibernate:
        format-sql: true
        ddl-auto: none
